#server
#server:
#  port: 8201
  
spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
    
#配置 eureka 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    
#配置feign
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  #暴露端口
        
 
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202
   
 
 
        
